### ISSUE TITLE
Solution Transfer Tool Enhancements - Transfer from different versions

### ISSUE THREAD

**Issue by bowens11** [MscrmTools/XrmToolBox#413] opened 2016-05-06 17:51 UTC
It would be a great feature to be able to transfer solutions from different versions. We are testing CRM 2016 in our Dev environment but before our testing has been completed, we needed to move a hotfix solution to our 2015 Test and Prod instances, but cannot because of versioning differences.

**Comment by MscrmTools** [comment] 2016-05-06 17:58
Even if it would be great to be able to implement it, I'm not sure it is possible. Even CRM application cannot do it.

It would require to strip out all CRM 2016 specific information before importing. Too much complicated to handle all possibilities. 

If someone wants to comment or give hints on how to achieve this, I'm ready to listen

**Comment by tlorenzo1** [comment] 2016-05-09 15:47
The MSCRMToolKit, has the ability to make "Profiles" of solutions, the problem is they don't offer the ability to order the solutions.

**Comment by MscrmTools** [comment] 2016-05-16 12:33
Closing this issue as no additional feedback

**Closed by MscrmTools** 2016-05-16 12:33 UTC
