### ISSUE TITLE
Upgraded XrmToolBox and plugins now fails CsvHelper not found

### ISSUE THREAD

**Issue by DianeF1** [MscrmTools/XrmToolBox#725] opened 2018-02-19 16:35 UTC
I updated my XrmToolBox this morning.  Now it will not open and shows an error on the following.  Where can this dll be obtained?

XrmToolBox
    Assembly Version: 1.2018.1.20
    Win32 Version: 1.2018.1.20
    CodeBase: file:///D:/XrmToolBox/XrmToolBox.exe

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'CsvHelper, Version=6.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' or one of its dependencies. The system cannot find the file specified.
File name: 'CsvHelper, Version=6.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'
   at XrmToolBox.PluginManagerExtended.Initialize()
   at XrmToolBox.MainForm.<MainForm_Load>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by MscrmTools** [comment] 2018-02-19 16:39
It seems one of the plugin is using a third party dll that is missing.

Did you install plugins lately? if so, you can try to delete them from the Plugins folder

**Comment by DianeF1** [comment] 2018-02-19 17:04
I've installed all plugins but the following - do any of them just not work with Xrm?

Early Bound Generator
Easy Translator
Export to Excel
GT Bulk Record Assigner
GT Solution Importer
GT Users Creator

**Comment by MscrmTools** [comment] 2018-02-19 17:09
Try to remove this one : GT Users Creator
It has been reported as showing errors sometime

**Comment by trovomenace** [comment] 2018-02-23 04:03
I have the same problem I also delete the folder and unzipped again but i have the same issue.

**Comment by MscrmTools** [comment] 2018-02-23 06:34
Did you delete XrmToolBox folder only? Plugins are stored in a different location, see Paths tab in Settings dialog

**Comment by DianeF1** [comment] 2018-02-23 12:25
I'm mostly working.  What I did was delete the folder C:\Users\<userid>\AppData\Roaming\MscrmTools\XRMToolBox.  Then when I opened XRMToolbox all the plugin's need to be installed.  I found that if I install all but these plugins I can keep it working. I;'m not thrilled with my solution but I guess it is as good as we can have at this time.

Early Bound Generator
Easy Translator
Export to Excel
GT Bulk Record Assigner
GT Solution Importer
GT Users Creator

**Comment by Boydski** [comment] 2018-02-23 19:29
Seems these types of errors continue to plague the XrmToolbox installer and have for literally years and multiple versions.

Isn't anyone regression testing the installer on new versions? That would, of course, require a clean installation by removing any semblance of if from the system. IE: Deletion of the "MscrmTools" folder as well as any and all Registry entries, before actually releasing to the public.

Then again, it's possible the onus is on the plugin developer, not the XrmToolbox container devs. So apologies if my assumptions are misplaced.

In the meantime, I'm off to implement yet more workarounds for the latest installer debacle. Sigh...

**Comment by MscrmTools** [comment] 2018-02-23 19:52
Well, you need to know that XrmToolBox is developed by one person, me!

So, no, I cannot test each and every configuration, plugins (more than 80) and so on before releasing a new version, new versions which by the way did not implement any change on how plugins are handled since more than a year.

So sorry if some users have troubles but I’m also using the update process to update my own usage of XrmToolBox and I got none of the issues mentioned here and I have all these plugins installed

**Comment by Boydski** [comment] 2018-02-23 22:53
Understood. And I back you 100%. Just note that I and my entire development team have had the same issue on multiple machines, with multiple personalized Windows development environments, over multiple versions of XrmToolbox, multiple versions of CRM/D365, over a period of years. Also, clients of ours with development teams that I've introduced the tool to over the years have had similar issues. And a quick search over the web shows it's a common issue.

This doesn't change our love of the tool. But it is what it is: Since the inception of the opening dialog with plugin installation selections, there have been bugs.

@DianeF1's solution above worked for us. Until the next update!

**Comment by MscrmTools** [comment] 2018-02-24 07:34
I’m not sure to understand...
Are the difficulties there since the introduction of Plugins Store ?
Or because the Plugins Store opens when XrmToolBox starts?
Or another scenario I did not understand?

**Comment by Boydski** [comment] 2018-02-24 16:59
Please see the attached screenshots in order along with the error log. These represent the current version. Per my previous mention, @DianeF1 figured it out and graciously shared how to work around the error.

The scenario I've provided you here has been a regular occurrence with the installer since the Plugin Installation Dialog was incorporated into the product. Once in a blue moon a version comes out with no issues. Most times, it's predictably broken. It's one of the reasons no one on our development team updates plugins or the XrmToolbox container itself very often. Only when we're willing to spend the time to debug the errors we know we'll get.

I recognize this may be within the individual plugins themselves. But maybe it's possible to have better error handling from within the container as well? At least one that wouldn't make the entire app crash after that. IE: Once the error occurs, XrmToolbox is a dead stick; it'll never work. One must delete the cache in the Roaming folder first, then reinstall with the workarounds in place in order to recover.

I hope this helps. And I empathize with you all the way brother. ;) Keep up the good work. You're amazing and XrmToolbox is amazing. We've been using it nearly since you introduced it.

![shoti](https://user-images.githubusercontent.com/115074/36632836-beced68a-1959-11e8-846c-691081667209.png)
![shotii](https://user-images.githubusercontent.com/115074/36632837-c19161a8-1959-11e8-9206-6bba6d3021a7.png)
![shotiii](https://user-images.githubusercontent.com/115074/36632839-c4547042-1959-11e8-8b8f-a09cc4a2463d.png)
![shotiv](https://user-images.githubusercontent.com/115074/36632842-c75994a2-1959-11e8-957a-c5eaba6df56e.png)
[XrmToolboxPluginInstall.log](https://github.com/MscrmTools/XrmToolBox/files/1754658/XrmToolboxPluginInstall.log)

**Comment by MscrmTools** [comment] 2018-02-24 17:12
Thank you for all these information. I will check if I can improve this scenario.

Nevertheless, there is no need to install ALL plugins. Just download those you need.

Some additional info:
- you can ask that Plugins Store does not show when XrmToolBox starts (see Settings)
- Installing ALL plugins means they all need to be downloaded. That is what is taking so much time. I will try to add info about the download progress.
- clearly, this error comes from individual plugins I don’t manage. I will check if I can improve error handling.

**Comment by Boydski** [comment] 2018-02-24 17:25
Well, the thing is, "Necessity is the mother of invention." We **want** to see the plugin store (already aware of the switch to turn it off). We want to see the latest & greatest folks have come up with. We actually have our own internal backlog of XrmToolbox widgets we'd like to create ourselves if we can find the time. Plus it has all the updates.

Developers out there have all kinds of *awesome* ideas! Sometimes we cannot wait to see what new widgets folks have come out with. We do Lunch & Learns where we'll just sit there and go through the new items we see on the XrmToolbox radar. Can't do that so much if we're cherry picking things. We'd rather install everything and keep everything up to date. It makes for a much better overall experience with the usage of the tool with our clients.

And our internet here is a gig up and a gig down. We're not worried about how much bandwidth we're hogging around here. ;)

And yes, clearly not on you Good Sir; I'm with ya. The "CsvHelper" seem to be responsible. And same type of error anyone who's been a middle-ware developer has experienced multiple times in their career. It happens.

Good luck brother.

**Comment by dennislutjohann** [comment] 2018-03-12 19:47
I think I have a solution. What I did was the following. I went to this location \AppData\Roaming\MscrmTools\XrmToolBox\NugetPlugins\AuditHistoryExtractor.1.0.1.14\lib\net462\Plugins and copied the CSVhelper.dll in the \AppData\Roaming\MscrmTools\XrmToolBox\Plugins\ directory. XRMtoolbox started with no issues. I didn't test all the plugins but it started :) If a plugin crashes again I will give a heads up.

**Comment by Boydski** [comment] 2018-03-12 20:12
Thanks for the input @dennislutjohann. However, to make things work, we've all been hacking the XrmToolbox post-install for a while. The creator of CSVhelper needs to fix their portion of the installer so folks don't have to continue to hack as we have been. ;)

**Comment by MscrmTools** [comment] 2018-03-12 20:35
The problem is not with csvhelper itself but with people using this assembly with different version without merging it in their own plugins.
This make a conflict between different plugins using same assembly with different version.

I have a new release almost ready that identifies faulting plugins.

**Comment by Boydski** [comment] 2018-03-12 23:26
Understood. Looking forward to the updates!

**Comment by MscrmTools** [comment] 2018-03-29 11:27
Should be fixed now.

Can you confirm?

**Comment by DianeF1** [comment] 2018-03-29 11:31
I downloaded and installed not only the update but all plugin’s and have been able to successfully use the tool.  Thank you!

Diane Fuller
Application Architecture
Spirit AeroSystems, Inc.

**Closed** 2019-01-30 15:59 UTC
