### ISSUE TITLE
v.1.2061.6.29 Crashes XrmToolBox when connection to CRM 8.0.1.344

### ISSUE THREAD

**Issue by kfehribach** [MscrmTools/XrmToolBox#477] opened 2016-08-22 15:50 UTC
When trying to connect to CRM XrmToolbox throws up the message: XrmToolBox has stopped working. 

When I check the XrmToolBoxConnection.log I get the error message:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source  : mscorlib
Method  : HandleReturnMessage
Date    : 8/22/2016
Time    : 10:44:17 AM
Error   : Access is denied.
Stack Trace : Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
#    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)

I see the access denied message in their but am confused because it had allowed me to create the connection. Second part of that is that even if it is a permissions issue I wouldn't expect the tool to crash.

**Comment by MscrmTools** [comment] 2016-08-22 15:56
Never seen this one and I'm not sure it is related to the organization version.
Where is the tool executed from? (I'm talking about folder path, just to be sure you are not in a specific folder that requires privilege elevation)

**Comment by shytikov** [comment] 2016-08-24 09:47
Is it CRM Online?

**Comment by joenewstrom** [comment] 2016-08-30 14:59
@MscrmTools might be a duplicate of the issue I just reported. Same db version for me, crashes only when authenticating after initiating plugin loading. If I authenticate first, then load plugin, no crash.

Yes CRM Online for me.

**Comment by MscrmTools** [comment] 2016-12-09 10:38
Closing, please reopen if still happens

**Closed by MscrmTools** 2016-12-09 10:38 UTC
