### ISSUE TITLE
Connection resets port to 80

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#260] opened 2015-10-13 06:06 UTC
Creating a connection to an LCS environment, which are by default installed with port 5555:
![image](https://cloud.githubusercontent.com/assets/2572253/10447014/b1bfa43e-7180-11e5-9329-d48875a03f69.png)

Connection works ok, the organization is found etc.
But when trying to connect later, the connection cannot be made. Checking the connection, the port has been reset to 80. Checking the config file shows that port 5555 is saved in the file, but apparently not read from file properly.
So I cannot connect to the org at all since it will always try with port 80.

**Comment by MscrmTools** [comment] 2015-10-14 15:53
Hi @rappen, I don't have any deployment on specific port. Can you check the port number saved in the connections file ?

**Comment by rappen** [comment] 2015-10-14 17:06
As mentioned in my original post, 5555 is stored in the file. ;)
Try manually editing the config file and opening that connection, you will see it is restored to 80.
I'm not sure, maybe @shytikov has started to look into this?

**Comment by MscrmTools** [comment] 2015-10-15 11:40
The value is read from the file as expected. The problem is elsewhere: When using a connection, the url is not recomposed from the value provided but from the result of the discovery service (it uses Organization Service Url, actually).
If this url is based on port 80, that means your deployment may be badly configured. Look in the deployment manager properties, in Web address tab to see if port 5555 is specified correctly

**Comment by rappen** [comment] 2015-10-15 12:29
This environment is actually provisioned by LCS, so it is all Microsoft setting it up...
For other reasons I have now killed the environment, but the problem is still showing up, without any chance for XTB to connect to the discovery service.

This is the connection info from mscrmtools2011.config:
```
    <ConnectionDetail>
      <AuthType>ActiveDirectory</AuthType>
      <ConnectionId>d4995680-db41-4e2d-ba33-f864ed6b6cd9</ConnectionId>
      <ConnectionName>JR LCS 1</ConnectionName>
      <IsCustomAuth>true</IsCustomAuth>
      <UseIfd>false</UseIfd>
      <UseOnline>false</UseOnline>
      <UseOsdp>false</UseOsdp>
      <UserDomain>contoso</UserDomain>
      <UserName>cadmin</UserName>
      <UserPassword>SomethingSomething</UserPassword>
      <SavePassword>true</SavePassword>
      <UseSsl>false</UseSsl>
      <ServerName>crm2015-devtest-jr-lcs-1-crm-a-6bfe9b7913f281e4.cloudapp.net</ServerName>
      <ServerPort>5555</ServerPort>
      <Organization>crmorg</Organization>
      <OrganizationUrlName>crmorg</OrganizationUrlName>
      <OrganizationFriendlyName>crmazure</OrganizationFriendlyName>
      <OrganizationServiceUrl>http://crm-32e2eed94b7:5555/crmorg/XRMServices/2011/Organization.svc</OrganizationServiceUrl>
      <OrganizationVersion>7.0.1.129</OrganizationVersion>
      <HomeRealmUrl />
      <Timeout>1200000000</Timeout>
      <WebApplicationUrl>http://crm-32e2eed94b7:5555/crmorg</WebApplicationUrl>
      <LastUsedOn>01/01/0001 00:00:00</LastUsedOn>
    </ConnectionDetail>
```
Opening this connection by clicking Manage Connections, shows me the connection dialog with port 80, before trying to connect at all.

**Comment by MscrmTools** [comment] 2015-10-15 12:44
OK! There is two problems, actually
1/ The edition of a connection has a bug as It displays port 80 whatever the port is. This is just a display bug
2/ You cannot connect because of LCS really bad configuration! As you can see in your XML file, the OrganizationServiceUrl is not a FQDN URL, this is the reason why you cannot connect.

To fix this quickly, just replace the hostname crm-32e2eed94b7 with crm2015-devtest-jr-lcs-1-crm-a-6bfe9b7913f281e4.cloudapp.net and you should be good to go

**Comment by rappen** [comment] 2015-10-15 12:46
Perhaps Microsoft should be notified about this really bad configuration.... let's say, by an MVP for example... ;)
I just clicked next-next-next-finish when I set it up.

**Comment by MscrmTools** [comment] 2015-10-15 13:34
I will try to find the appropriate contact in CRM product group

**Comment by MscrmTools** [comment] 2015-10-15 14:43
Answer from Product Team : This is a known issue and this will be fixed in the future. No ETA.

**Closed by MscrmTools** 2015-10-15 14:43 UTC

**Comment by shytikov** [comment] 2015-10-15 15:25
Best answer ever!

**Comment by MscrmTools** [comment] 2015-10-15 15:26
No ETA is my own personal opinion, I did not get statement about ETA

**Comment by rappen** [comment] 2015-10-15 15:28
Thank you for info.
Will the display issue (showing 80 when it is actually something else) be fixed?

**Comment by MscrmTools** [comment] 2015-10-15 15:29
yes, I'm on it as I write this comment

**Comment by rappen** [comment] 2015-10-15 15:31
Great, just askes as you marked this issue as closed :)

**Comment by MscrmTools** [comment] 2015-10-15 15:33
yes, I closed it too fast. But I will check in the change right now
