### ISSUE TITLE
Site map changes creates several issues with the most recent records menu

### ISSUE THREAD

**Issue by Hans87** [MscrmTools/XrmToolBox#151] opened 2015-06-14 18:04 UTC
Hi, i have MS CRM 2015 update 1 and trying to disable some entities in the site map to make the menu look more slim. But after uploading the site map the system start bugging like crazy. Every time i try to choose a entity or refreshing the page an error occur. The usual "do you want to send it to Microsoft" message error. In the error it seems like the problem is in the menu part with "most recently open records" or the new search field.
![image](https://cloud.githubusercontent.com/assets/12731136/8149771/a5a77d16-12d0-11e5-8ca6-d4c19a765ff4.png)

![image](https://cloud.githubusercontent.com/assets/12731136/8149767/930d4c9e-12d0-11e5-8f04-c522b1713255.png)

The error message varies but these are some of them:

"Uncaught Sys.InvalidOperationException: Sys.InvalidOperationException: Service ActivityFeeds.UI.IActivityFeedService is not registered with this instance"

"Uncaught Sys.InvalidOperationException: Sys.InvalidOperationException: Service Xrm.Interfaces.Services.IMostRecentlyViewedService already has an implementation"

The problem totaly make the system crash and restart the session in the browser. Tried both IE and Chrome in several compability settings but nothing work. Tried to set the sitemap to default again but the problem still occurs. 

Tried to start a new Trial version and not using the Site map editor and none of the problem occurs again.

Please help me with this

**Comment by MscrmTools** [comment] 2015-06-15 07:15
Can you try to remove entities instead of disabling them? Does the problem occurs?

**Comment by MscrmTools** [comment] 2016-01-05 10:52
6 months without feedback, I close this issue. Please reopen if needed

**Closed by MscrmTools** 2016-01-05 10:52 UTC
Labels: Waiting for analysis

**Comment by TimDarius** [comment] 2016-03-24 20:34
We ran into this issue as well while attempting to reproduce a customized sitemap issue. It turned out to be a hard-coded, but incomplete Url assigned to some custom navigation. It had been ported from a CRM Online org https colon //genericorg.crm.dynamics.com/path to an on-premises org and was rewritten as http://server (without the org and the path). The navigation needed to be http://server/org/path and after making the correction, the highly frequent script exceptions disappeared.

**Comment by MscrmTools** [comment] 2016-03-24 20:39
Thank you for finding the root cause of this issue

**Comment by Pradeep-Bhat** [comment] 2016-04-22 09:10
Hello Tim Darius, We are having the same issue in our organization. Would you mind sharing some more details as to where exactly the issue was found in the code.
Thanks
Pradeep
