### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mkapde** [MscrmTools/XrmToolBox#1060] opened 2021-08-11 15:51 UTC
Access Restricted environment, XRMToolbox latest version is installed on network shared drive. Short cut created on SSO workstation mahcine,
When try to launch failed with below error. 
I already tried IntenetProxy setting in connection file and not able to launce it. failed with same error as below

Unhandled exception has occurred in your application. ... 
An invalid argument was supplied.
--------- Exception Text --------
System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied.

Any help is appriciate!

**Comment by BetimBeja** [comment] 2021-08-23 05:49
Duplicate of #1043

**Closed** 2021-09-13 07:38 UTC
Labels: bug
