### ISSUE TITLE
[BUG] Unable to scroll in Synchronous Events Execution Order Editor

### ISSUE THREAD

**Issue by samalex1701** [MscrmTools/XrmToolBox#1056] opened 2021-07-21 20:51 UTC
**Describe the bug**
When loading events from organization more entities are listed than can be displayed on the screen in left panel.  There is no scroll bar to view the ones that go off screen.  

**To Reproduce**
Currently it only shows entities up to those starting with 'M' since that's at the bottom of the visible list and if I select the last one visible I can continue to arrow down though the visible items don't move or is there a scroll bar to move the list down.  

**Expected behavior**
Scroll bars need to exist so I can move the list up and down to view all items as our list is larger than can fit on the screen.

**Screenshots**

**Desktop (please complete the following information):**
 - XrmToolbox Version 1.2021.6.51
 - Tool version 1.2921.2.2

**Additional context**

**Comment by MscrmTools** [comment] 2021-07-22 06:56
Duplicate of https://github.com/MscrmTools/MsCrmTools.SynchronousEventOrderEditor/issues/1

**Closed by MscrmTools** 2021-07-22 06:56 UTC
Labels: bug
