### ISSUE TITLE
Metadata Browser: Picklist Value Display Error

### ISSUE THREAD

**Issue by yinseny** [MscrmTools/XrmToolBox#156] opened 2015-06-22 08:07 UTC
Varsion: 1.2015.6.9

All Picklist Values displayed as "MsCrmTools.MetadataBrowser.AppCode.OptionMd.OptionMetadataInfo"

![2015-06-22 16_00_50-xrmtoolbox for microsoft dynamics crm 2011_2013_2015 v1 2015 6 9](https://cloud.githubusercontent.com/assets/863430/8277726/2f144fde-18f8-11e5-8d1c-9f21a08fb7b1.png)

**Comment by MscrmTools** [comment] 2015-06-22 08:24
Hi,

Yes this is a known bug and I'm struggling to find the cause of this behavior. The code did not change so I can't figure out why it does not show details anymore.

I guess it can come from updating SDK assemblies to 7.0 ones

I need to make some more research so I don't have an ETA for resolution

**Comment by miller1976** [comment] 2015-06-24 14:10
Hi MscrmTools

Is it just me -or- could this be fixed by implementing an overwrite of the ToString() method on the OptionMetadataInfo object?

The default implementation is to take the typename of the object, which it seems is what is done. So adding a ToString() that would yield the label should probably solve the problem.

**Closed** 2015-07-18 13:07 UTC
Labels: bug
