### ISSUE TITLE
[BUG] Unable to connect to dynamics 365 instance online thru connection wizard

### ISSUE THREAD

**Issue by vnathglo** [MscrmTools/XrmToolBox#1035] opened 2021-05-21 21:01 UTC
**Describe the bug**
Unable to connect to dynamics 365 instance online using v1.2021.4.47 using connection wizard which was working till 5/18/21. Receiving the below errors all of a sudden. 

1. Error thru connection wizard FCB 'EnableRegionalDisco' is disabled

![image](https://user-images.githubusercontent.com/56888332/119197544-89147700-ba4d-11eb-97dd-cc480dc3466e.png)

2.Error thru SDK: Source	: Not Provided
Method	: Not Provided
Date	: 5/21/2021
Time	: 1:51:47 PM
Error	: You don't have permission to access any of the organizations in the Microsoft Common Data Service region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CDS region and try again. Otherwise check with your CDS administrator.
Parameter name: USG
Stack Trace	: Not Provided

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
Should be able to connect to crm instance 

**Screenshots**
![image](https://user-images.githubusercontent.com/56888332/119197611-a8ab9f80-ba4d-11eb-82cc-8f91b5edd071.png)

**Desktop (please complete the following information):**
 - XrmToolbox Version - v1.2021.4.47
 - Tool version

**Additional context**

**Comment by MscrmTools** [comment] 2021-05-22 05:48
It's likely a change in your tenant + maybe the need to update SDK assemblies for SDK control.
I will release a new version next week that will eventually fix the SDK control.
Can you try to connect with Oauth method, please?

**Comment by vnathglo** [comment] 2021-05-24 17:12
> It's likely a change in your tenant + maybe the need to update SDK assemblies for SDK control.
> I will release a new version next week that will eventually fix the SDK control.
> Can you try to connect with Oauth method, please?

Hi, where in the tenant administration would this have been changed? I wanted to mention that it is able to connect using connection string. It is also connecting thru oauth method. Its the connection wizard/sdk based logons that stopped working after 5/19/21. 

Thanks

**Comment by vnathglo** [comment] 2021-05-24 17:35
Via the connection wizard, It keeps referring to 'enableregionaldisco' being disabled.

![image](https://user-images.githubusercontent.com/56888332/119385875-6a4ff380-bc8c-11eb-8e7f-2e7c51d5d5f6.png)


Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/21/2021 3:57:18 PM  Unable to connect to CRM: FCB 'EnableRegionalDisco' is disabled
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 5/21/2021
Time	: 3:57:18 PM
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/21/2021 3:57:18 PM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/21/2021 3:57:18 PM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 5/21/2021
Time	: 3:57:18 PM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Comment by TooSAD4** [comment] 2021-05-25 01:30
I'm having the same issue and it started around mid last week. I wonder if it has anything to do with the regional discovery service being shutdown. It says on the following url that it will be shutdown after April 21, 2021. 

https://docs.microsoft.com/en-us/power-platform/important-changes-coming#regional-discovery-service-is-deprecated

**Comment by MscrmTools** [comment] 2021-05-25 06:40
This is likely the root cause of the issue.

I have a new version of XrmToolBox coming in the next hours that should fix this by using latest Microsoft assemblies

**Comment by MscrmTools** [comment] 2021-05-25 12:24
@vnathglo  and @TooSAD4 , can you check with latest version that just has been released?

**Comment by MscrmTools** [comment] 2021-05-25 15:53
It does work for me on a crm4.dynamics.com environment. What is yours?

You can use Oauth method instead

**Comment by TooSAD4** [comment] 2021-05-25 16:00
crm9.dynamics.com
I'm currently using the connection string and that works. I haven't tried Oauth because I would have to make a request to another department in charge of managing our Azure AD.

**Comment by vnathglo** [comment] 2021-05-25 16:16
> @vnathglo and @TooSAD4 , can you check with latest version that just has been released?

Hi,

- Updated xrmtoolbox to 1.2021.5.47 this morning
- Tried connecting using connection wizard and now receiving the below error
- Can still however connect successfully using the connection string

ERROR WITH CONNECTION WIZARD

icrosoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 10:57:21 AM  Initialize CRM connection Started - AuthType: AD
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	5/25/2021 10:57:21 AM  Discovery URI is = https://{crminstancename}.dynamics365portals.us:443/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	5/25/2021 10:57:21 AM  DiscoverOrganizations - Initializing Discovery Server Object with https://{crminstancename}.dynamics365portals.us/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	5/25/2021 10:57:21 AM  DiscoverOrganizations - attempting to connect to CRM server @ https://{crminstancename}.dynamics365portals.us/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 10:57:22 AM  Unable to login to Dynamics CRM, Error was : Metadata contains a reference that cannot be resolved: 'https://{crminstancename}.dynamics365portals.us/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Source	: System.ServiceModel
Method	: Retrieve
Date	: 5/25/2021
Time	: 10:57:22 AM
Error	: Metadata contains a reference that cannot be resolved: 'https://{crminstancename}.dynamics365portals.us/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 5/25/2021
Time	: 10:57:22 AM
Error	: The remote server returned an error: (500) Internal Server Error.
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 10:57:22 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 10:57:22 AM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 5/25/2021
Time	: 10:57:22 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Comment by vnathglo** [comment] 2021-05-25 16:22
With v1.2021.5.47 trying to connect to crm9 with connection wizard returns the same error. Connection string still works.

![image](https://user-images.githubusercontent.com/56888332/119533201-3be51d80-bd4b-11eb-8bcc-afa2651ae335.png)
LOG


Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 11:19:07 AM  Unable to connect to CRM: FCB 'EnableRegionalDisco' is disabled
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 5/25/2021
Time	: 11:19:07 AM
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer, Boolean useGlobal)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 11:19:07 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	5/25/2021 11:19:07 AM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 5/25/2021
Time	: 11:19:07 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

**Comment by MscrmTools** [comment] 2021-05-25 16:26
@TooSAD4, using default configuration of OAuth, you shouldn't have to ask help to your Azure colleagues

**Comment by MscrmTools** [comment] 2021-05-25 16:27
@vnathglo I receive your first version by email...

what is this https://{crminstancename}.dynamics365portals.us:443/XRMServices/2011/Discovery.svc url?? never seen dynamics365portals.us before

**Comment by TooSAD4** [comment] 2021-05-25 16:35
Using the development Azure App ID and reply url works.

**Comment by vnathglo** [comment] 2021-05-25 16:49
> @vnathglo I receive your first version by email...
> 
> what is this https://{crminstancename}.dynamics365portals.us:443/XRMServices/2011/Discovery.svc url?? never seen dynamics365portals.us before

Yes that was by mistake so I deleted it, I had put in the wrong dynamics url when trying to connect. But after putting in the correct crm9 url also, it's failing, thru the connection wizard approach.

**Comment by vnathglo** [comment] 2021-05-25 16:50
So for v1.2021.5.47
- Can connect thru oauth and development azure app id
- Can connect thru connection string
- CAN NOT connect thru the connection wizard

**Comment by vnathglo** [comment] 2021-05-25 16:56
authtype=Office365

**Comment by MattB-msft** [comment] 2021-05-25 18:12
Office365 Auth is the issue.. 
if you use the SDK Login Control,  does this work for you now?   No other changes?

**Comment by vnathglo** [comment] 2021-05-25 20:39
No the SDK Login control does not work in this version. See the attached screenshot

![image](https://user-images.githubusercontent.com/56888332/119565256-5fba5a80-bd6f-11eb-92ff-e1e5a07fcb36.png)

**Comment by MattB-msft** [comment] 2021-05-25 21:04
Can you post the version number of the Microsoft.Xrm.Tooling.Connector.dll from the XrmToolbox your using?
and your trying to connect to an instance in USG right?

**Comment by vnathglo** [comment] 2021-05-26 02:30
@MattB-msft yes to USG. The dll version is 4.0.0.88

![image](https://user-images.githubusercontent.com/56888332/119593874-61504680-bda0-11eb-9dd4-725e6c42ae8a.png)

**Comment by MattB-msft** [comment] 2021-05-26 04:13
Interesting.. that version is correct,, 
to access USG you would need to click "Show Advanced", then select the Regions drop down and choose "US Gov High" from that list. 

then click login ( leave User name / PW blank ) 

You should get a AAD Login dialog,, login normally.. 

let me know of that does not work. 

MattB

**Comment by steffenhds** [comment] 2021-05-26 12:30
I had exact same issue as @vnathglo in government cloud and connection wizard worked.  Using the MS Login Control (SDK Login) and using Advanced Settings, when selecting  Region: Govt Cloud High , my login was not recognized. But selecting North America Region 2 , was able to login now. So gcc is in in North America 2 unless you are gcc high or gcc dod.

**Comment by steffenhds** [comment] 2021-05-26 12:31
update to my last post: I had exact same issue as @vnathglo in government cloud and connection wizard worked, previously.

**Comment by MatthewTheRaven** [comment] 2021-05-26 15:23
I had the same issue and also was able to login with the latest by using NA2 for a GCC instance. Might not be a bad idea to label it "North America 2 / GCC".

**Comment by vnathglo** [comment] 2021-05-26 15:52
> I had the same issue and also was able to login with the latest by using NA2 for a GCC instance. Might not be a bad idea to label it "North America 2 / GCC".

Ditto. Specifying NA2 specifically for GCC thru the sdk control works.

**Comment by TooSAD4** [comment] 2021-05-26 17:19
that works for me tool

**Comment by MattB-msft** [comment] 2021-05-26 20:08
@MatthewTheRaven  Yea,, been meaning to do that for a while... Will see if I can get that done in the next release or 2. 
thanks !

**Comment by MattB-msft** [comment] 2021-05-26 21:37
@vnathglo , if this resolves it for you can you close this thread?

**Closed** 2021-06-01 22:34 UTC
Labels: bug
