### ISSUE TITLE
SiteMap Editor only shows CRM 2011 SubAreas

### ISSUE THREAD

**Issue by MDoddio** [MscrmTools/XrmToolBox#396] opened 2016-04-10 17:30 UTC
I cannot figure out why the SiteMap editor is only showing CRM 2011 SubArea. I cannot access any of the new SubAreas, such Activity Feeds (What's New), Service Management, Email Settings (social), etc. 

Has anyone else reported this issue?

-Dodd

**Comment by MscrmTools** [comment] 2016-04-10 17:43
Never heard this

What version of CRM? Come from an upgrade?

**Comment by MDoddio** [comment] 2016-04-10 21:12
Latest version of the XrmToolBox, CRM Online for Government and CRM Online commercial. 
Some of the instances have solutions from CRM 2013/2015, others are net new solutions. All of them only show Areas and Subareas from CRM 2011. In fact, the config file in the root folder is titled mscrmtools2011.config

**Comment by MscrmTools** [comment] 2016-04-11 06:59
The config file is for connection. The name is a legacy of first versions of XrmToolBox. So this is not the cause of your issue.

**Comment by MDoddio** [comment] 2016-04-11 13:21
Got it. Any ideas then why I'm not seeing the CRM 2016 areas/Subareas?

**Comment by MscrmTools** [comment] 2016-04-12 13:04
Can you provide your SiteMap xml ?Not the one from SiteMapEditor but the one when exporting it through solutions?

**Comment by MDoddio** [comment] 2016-04-12 14:15
Sure.

**Comment by MscrmTools** [comment] 2016-04-28 11:30
So? Where is your sitemap?

**Comment by MscrmTools** [comment] 2016-05-28 15:25
Closing this issue since I did not heard from you since a month and half.
Please reopen the issue if needed

**Closed by MscrmTools** 2016-05-28 15:25 UTC
Labels: Waiting for analysis
