### ISSUE TITLE
License file is not recognized

### ISSUE THREAD

**Issue by sjarrell** [MscrmTools/XrmToolBox#841] opened 2019-02-24 21:19 UTC
I have donated and received my license xml file, however when I place it in the C:\Program Files (x86)\XrmToolbox directory I am still receiving the Donate message. Any suggestions?

Thanks,

Steve

**Comment by MscrmTools** [comment] 2019-02-28 19:13
I think I see what the problem is.
A file might be missing in XrmToolBox zip file. Can you try to add this file too in your XrmToolBox folder?
[McTools.StopAdvertisement.zip](https://github.com/MscrmTools/XrmToolBox/files/2916520/McTools.StopAdvertisement.zip)

**Comment by sjarrell** [comment] 2019-02-28 19:21
Thanks. We'll give it a try!

**Comment by MscrmTools** [comment] 2019-04-03 05:19
@sjarrell Any news?

**Comment by sjarrell** [comment] 2019-04-03 17:44
@MscrmTools Unfortunately I'm still seeing it (see attachment). I do have McTools.StopAdv.xml and McTools.StopAdvertisement.dll placed in the main program folder.
![XMLToolbox](https://user-images.githubusercontent.com/47953101/55500522-84469c00-5616-11e9-8081-c64ff8032252.jpg)

**Comment by MscrmTools** [comment] 2019-04-03 17:54
Ok, let me check this!

**Comment by MscrmTools** [comment] 2019-05-24 11:22
I tested it and it worked as expected... Don't know what is happening here

**Comment by MscrmTools** [comment] 2019-06-06 07:39
Should be fixed in next release

**Closed by MscrmTools** 2019-06-06 07:39 UTC
