### ISSUE TITLE
Error connecting to organisation 

### ISSUE THREAD

**Issue by StephaneSeguin** [MscrmTools/XrmToolBox#482] opened 2016-08-28 15:49 UTC
The value cannot be null
Parameter name : S
( French La valeur ne peut pas être Null. Nom Du paramètre :S)

Version: 1.2016.8.23

**Comment by MscrmTools** [comment] 2016-08-29 07:42
Hi Stéphane,

Can you be more specific on the target organization and the authentication mode in use?

Also:
To get more information on why the connection did not succeed on your organization, please activate the trace by following [this procedure](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox)

Then, please post the log here so we can analyze what the problem is

**Comment by MscrmTools** [comment] 2016-09-23 12:14
I close this issue since I got no feedback.
Please reopen the issue if you want to provide additional information

**Closed by MscrmTools** 2016-09-23 12:14 UTC
