### ISSUE TITLE
Erro when try to connect in crm online

### ISSUE THREAD

**Issue by michaelfp** [MscrmTools/XrmToolBox#446] opened 2016-06-29 19:18 UTC
XrmToolBox Version 1.2016.5.27

![image](https://cloud.githubusercontent.com/assets/1903203/16465399/d4c2829c-3e14-11e6-849a-7b7d00887e5d.png)

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Sdk
Method	: ThrowIfNull
Date	: 29/06/2016
Time	: 16:08:52
Error	: Valor não pode ser nulo.
Nome do parâmetro: identityProvider
Stack Trace	: em Microsoft.Xrm.Sdk.ClientExceptionHelper.ThrowIfNull(Object parameter, String name)
   em Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   em Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   em Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   em Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   em Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   em Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   em Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   em Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

I had made a test in many organization without result. in the last two versions i had this problem. I removed either PluginRetriever or DLabar, but the problem still.

**Comment by MscrmTools** [comment] 2016-06-29 19:30
This [thread](https://community.dynamics.com/crm/f/117/t/147252) seems to talk about the same problem and leads to username problem. 
Do you use a CRM Online federated with your local AD? If so, try to change the username to email address format or domain\username format (depending on what you tested)

**Comment by michaelfp** [comment] 2016-06-29 19:51
no i´m using onmicrosoft.com user

**Comment by MscrmTools** [comment] 2016-06-29 19:55
I'm using XrmToolBox against this kind of CRM online almost everyday without any problem...
Are you sure to use the appropriate email address?
You can send me screenshots of your configuration by email if you want => tanguy92[at]gmail[dot]com

**Comment by Customery** [comment] 2016-07-27 03:00
I've encountered the same error trying to authenticate Xrmtoolbox 1.2016.6.29 with CRM Online. I'll update this issue once I resolve the problem.

**Comment by Customery** [comment] 2016-07-27 10:53
With Tanguy's help, I confirmed that the issue was caused by a firewall configuration in our corporate firewall. I was able to connect to the same instance on the same computer with the same credentials from home. But when I connected to the VPN, the issue reappeared.

**Comment by MscrmTools** [comment] 2016-08-17 09:48
@michaelfp Can you confirm it's also a corporate network issue?

**Comment by MscrmTools** [comment] 2016-09-23 12:19
No answer, closing the issue

**Closed by MscrmTools** 2016-09-23 12:19 UTC
