### ISSUE TITLE
Error when retrieving organisations after upgrade to Windows 10

### ISSUE THREAD

**Issue by MikeBrett1** [MscrmTools/XrmToolBox#220] opened 2015-08-26 16:55 UTC
After upgrading to Windows 10 and trying to create or use a connection, the message

'An error occurred while retrieving organizations: The requested service provider could not be loaded or initialized'

is displayed.

**Comment by MscrmTools** [comment] 2015-08-26 20:32
I'm using windows 10 since a month and had no problem to use Xrmtoolbox.
There must be something else

**Comment by MikeBrett1** [comment] 2015-08-27 06:44
Any idea what service the error message may be referring to?

Mike
Mobile: 07717 732778

**Comment by shytikov** [comment] 2015-08-27 07:02
May you reveal some connection details? Server installation type for example?

**Comment by MikeBrett1** [comment] 2015-08-27 07:40
Connecting to CRM online on the European server (crm4), so using Office365 authentication.  Happens on all 3 systems we have on that server.  No issues connecting directly..

Mike
Mobile: 07717 732778

**Comment by shytikov** [comment] 2015-08-27 07:56
Can you try to perform the same operation, but from different PC as well? Just to make sure, that problem is not specific to your box only...

**Comment by MscrmTools** [comment] 2015-09-07 09:43
I'm sorry but I really cannot reproduce

**Comment by MikeBrett1** [comment] 2015-09-08 08:34
Had to revert to Windows 8.1 as XrmToolbox not the only thing I cannot get to work.

Thanks.

Mike
Mobile: 07717 732778

**Comment by MscrmTools** [comment] 2015-09-08 09:00
Ok so maybe something was wrong on your Windows 10 but it does not seem related to XrmToolBox.

I close the issue

**Closed by MscrmTools** 2015-09-08 09:00 UTC
Labels: Can't reproduce
