### ISSUE TITLE
Crash on log in with MFA 

### ISSUE THREAD

**Issue by Diego-Saavedra-San-Juan** [MscrmTools/XrmToolBox#976] opened 2020-10-08 15:32 UTC
The program crashes when trying to log in to a dynamics online instance on the European datacenter (crm4.dynamics.com). My use has MFA/Azure log in. The MFA is not used from the internal network. 

This has been working fine in the previous version. For the first version in which it worked out of the box, we had to create the connections again so that they would work, so tested that in this version, but it doesn't make any difference. 

---
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.10.41

**Comment by Diego-Saavedra-San-Juan** [comment] 2020-10-08 15:34
It crashes also when configuring settings, ie, changing setting for data sending

**Comment by MscrmTools** [comment] 2020-10-08 16:05
Is there any error message? or it is just closing the program?

It seems to me that writing to file might be the cause of the issue as it affects connections and settings which are absolutly not related

**Comment by Diego-Saavedra-San-Juan** [comment] 2020-10-08 16:11
No, it just dissapears after a while. The process ends too.

**Comment by Diego-Saavedra-San-Juan** [comment] 2020-10-09 07:52
thank you for all help and for this great tool btw, always worth saying

**Comment by MscrmTools** [comment] 2020-10-09 11:57
Thanks...

Can you tell me where your XrmToolBox storage folder is located? network drive? local drive?

**Comment by Diego-Saavedra-San-Juan** [comment] 2020-10-09 13:01
local drive. have found some wer files,  i'm unsure if they contain sensitive info so i have to wait to attach them.

**Comment by Diego-Saavedra-San-Juan** [comment] 2020-11-02 11:54
seems to be working now

**Closed** 2020-11-02 12:40 UTC
