### ISSUE TITLE
Allow for specifying Early Bound Entities Assembly

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#353] opened 2016-03-04 15:15 UTC
The Xrm Sdk will attempt to use any EarlyBound Assembly it can find: https://msdn.microsoft.com/en-us/library/gg328210.aspx  This creates an error if multiple assemblies exist.  We'll need to be able to call [EnableProxyTypes(Assembly)](https://msdn.microsoft.com/en-us/library/gg326003.aspx) from the plugin.

If you want to discuss this, let me know.  I don't believe I have time currently to implement it though, or I'd give a shot at a pull request.

Also thinking it might be good if the ToolBox had its own Early Bound Types, and then others could reference that, and it could be set by default, which could prevent errors if custom plugins haven't specified the assembly via the yet to be determined method requested in this issue.

**Comment by MscrmTools** [comment] 2016-04-28 11:48
I performed some test and it seems that the major problem here is that the `CrmServiceClient` constructor is looking into all loaded assemblies to find an assembly that enable proxy types. If multiple plugins implement their own types, then the connection fails.
So I'm not sure we can avoid this problem unless `XTB`implements its own Early Bound Types as you suggested.
So I will add a new assembly in the development solution to embed standard Early Bound Types

Any comments?

**Comment by daryllabar** [comment] 2016-04-28 19:31
You could just add my earlybound NuGet package if you want?  It would eliminate the need for me to have to use my own.  Without providing a way to set the assembly on the connection though, plugins won't be able to use their own custom earlybound assemblies...

**Comment by MscrmTools** [comment] 2016-04-28 19:39
Not that I don't want to do so, but I would like to avoid too much dependencies so if you don't mind, I could create my own...
Just to be sure, your earlybound is the standard one, without any specific implementation over CrmSvcUtil?

**Comment by daryllabar** [comment] 2016-04-28 19:46
There are some changes, For example, Option Sets are not generated by default.  Also I add another constructor to each entity to support Linq Queries better, and I add some typed OptionSet Enum Properties.  The base class doesn't change, and there are no new dependencies.

You can feel free to use the EarlyBoundGenerator and create your own so you don't need a new dll, and the name space maps, etc...

**Comment by MscrmTools** [comment] 2016-04-28 19:53
ok, thanks

**Comment by MscrmTools** [comment] 2016-05-02 08:53
@daryllabar Can I steal your code for Early Bound entities and just change the namespace to make it a XrmToolBox code?

**Comment by daryllabar** [comment] 2016-05-02 10:07
Nothing would make me happier.  You'll have to renamespace it every major release though.

**Comment by MscrmTools** [comment] 2016-05-02 10:13
I think I can live with that :)

Thanks!

So, I will add a new assembly which contains your code but renamespaced, so that evrybody can use it and remove his/her own early bound types

**Comment by daryllabar** [comment] 2016-05-02 10:16
Just an FYI... I can still see someone wanting to set their own assembly types if they are developing a Plugin that is not ment to be shared.  But for now, this will satisfy my needs. :)

**Comment by MscrmTools** [comment] 2016-06-14 12:46
I generated the Entities.cs file but it is really heavy! Does it make sense if I remove all "business" entities (account, contact, etc.) and include only "system" entities that deal with configuration/customization (savedquery, systemuser, pluginassembly, etc.)?

**Comment by daryllabar** [comment] 2016-06-27 19:33
Potentially... the cost is the download size is an extra 5-8 mb...  Is that a major issue?

**Comment by MscrmTools** [comment] 2016-06-27 19:51
Not really...

Scott Durow also mentions that if we use common entities assembly, it could still break "private" plugins that are using their own entities. Which is true.

I can try some scenario to see if it is possible to define proxy assembly per plugin but the first difficulty here is to find if the plugin does use a custom entities proxy and if yes, what is it. Maybe another interface can handle this

**Comment by daryllabar** [comment] 2016-06-27 19:55
I think we should define a new interface for that, and force the plugin to specify it.

**Comment by MscrmTools** [comment] 2016-06-27 19:58
I'm starting to design a test scenario...

**Comment by daryllabar** [comment] 2016-06-27 20:04
If you create a plugin that uses your EarlyBoundTypes, and create one that uses my early bound types, and both of them attempt to retrieve a Contact, that should work...

**Comment by MscrmTools** [comment] 2016-06-27 20:59
Ok, I made it work but two information :

1. Specifying an interface that return what assembly to use for earlybound entities is not enough. Indeed, when performing the connection (even without opening any plugin), a parsing of all assemblies seems to be performed to find proxy types. The only way I found to avoid this problem is to change the access level from "public" to "internal" for all types and enums. This way, EarlyBound types are not found by the connection process

2. If point 1 is respected and a connection can be performed, then specifying an interface to return the appropriate type seems to work. 

Code is finalized and commited in the master branch to provide a pre release version. Please test with your plugins as soon as it is available. The interface won't be mandatory because it would require to update ALL plugins which seems to much

**Comment by daryllabar** [comment] 2016-06-27 21:06
Shouldn't you only be creating a connection for the plugin to use, after it is created?  I thought each plugin got it's own connection?

**Comment by MscrmTools** [comment] 2016-06-27 21:10
Yes but if I run Xrmtoolbox and I decide to start a connection without opening a plugin, then the error occurs too

**Comment by daryllabar** [comment] 2016-06-27 21:17
Could you create a fall back assembly, with no types?  That would allow the initial connection to succeed...

**Comment by daryllabar** [comment] 2016-06-27 21:18
Right now my assemblies are in a shared dll so I don't have to bloat every single one of my assemblies...

**Comment by MscrmTools** [comment] 2016-06-27 21:19
Sleep time for me now... I will try tomorrow

**Comment by MscrmTools** [comment] 2016-06-28 14:40
After some digging, the problem is that CrmServiceClient (from new Tooling assemblies) does not seem to allow specifying Proxy Types
Event connection strings do not read Proxy Types attribute [as they did before](https://msdn.microsoft.com/fr-fr/library/gg695810(v=crm.7).aspx)

**Comment by daryllabar** [comment] 2016-06-28 17:20
So is that something that you can reach out to Microsoft to see who we are supposed to handle that?

**Comment by MscrmTools** [comment] 2016-06-28 17:33
I sent an email three hours ago... Hopefully, I'll get an answer

**Comment by daryllabar** [comment] 2016-08-08 14:41
Any response on that e-mail?

**Comment by shytikov** [comment] 2016-08-08 14:56
I think it's almost disaster.

From what I see, `CRM` classes automatically resolve early bound entities from current `AppDomain`. If there two or more assemblies with `ProxyTypesAssemblyAttribute` set, it fails.

I was thinking it would be possible to create another isolated `AppDomain` and call OrganizationService from there. And it's kind of possible, but basically means, that none of plugins will get their early bound entities resolved. The problem is also that `CrmServiceClient` not able to cross `AppDomain` boundaries, so we would need to create some kind of wrapper around it, sending correct arguments, that could be serialized.

Another idea would be to create separate `AppDomain` per plugin instance. And this is brilliant idea. Problem is that `WinForms` does not support `AppDomains`. So we cannot have main window working in one `AppDomain` and content of that window — from another. Unless we would involve some hacks, like `WPF` proxy layer... or maybe [this article using unsafe calls](http://do-the-right-things.blogspot.se/2009/07/cross-appdomain-winform-implementation.html).

I believe we also could try to use web-references. Basically not use `Tooling` assemblies, but instead use client generated from `wsdl`. Which would lead to massive connection issues (since WCF incredibly painful to configure from code).

I personally like second approach, and I think we need to invest some time to investigate possibility plugins separation using `AppDomains` with all imaginable shims and crutches... This might look ugly in the end, but we would get perfect isolation and safety.

**Comment by daryllabar** [comment] 2016-08-08 15:09
I was thinking about a third possibility, where I just remove the ProxyTypesAssemblyAttribute from my EarlyBoundEntities, and then create an IOrganizationService that wraps the current one, and converts all Non Generic CRM Entities to Entities before passing it onto the real one.  I'm not sure what magic CRM is doing in requiring a ProxyTypesAssemblyAttribute, but I don't see myself getting any benefit out of it.  I have to cast everything that get's returned anyway.  Maybe it's a requirement for Linq-to-CRM?  Not sure...

The result of this solution would be I can use EarlyBound, without creating a AppDomain issue.

**Comment by shytikov** [comment] 2016-08-08 15:13
I've tried this option, it doesn't worked for me. If assembly is not marked with `ProxyTypesAssemblyAttribute` it's not recognized as one containing early bound types...

But I would appreciate if someone else could confirm my results independently from me... Since maybe I did something not right...

**Comment by shytikov** [comment] 2016-08-08 15:36
Maybe we can just get rid of this attribute and manually cast late bound types to early bound? I need to check, it should not be that hard to come up with generic function doing this job.

**Comment by daryllabar** [comment] 2016-08-08 15:40
@shytikov Wrapping the IOrganizationService would perform the cast for you.  In previous versions of the SDK, you could manually specify you're EarlyBoundAssembly... @MscrmTools was waiting on a response from an e-mail as to what has happened with that functionality.

**Comment by shytikov** [comment] 2016-08-08 15:46
This is exactly what I've done. It accepts assembly as parameter (attribute was unset) and does nothing. That's why I'm interested maybe someone can do the same thing independently to verify.

**Comment by MscrmTools** [comment] 2016-08-08 15:55
@daryllabar did not get any response so far... I will try to ask again

**Comment by shytikov** [comment] 2016-08-08 20:46
One more idea... What if we declare all early bound classes as internal? Could be just simple as that...

**Comment by daryllabar** [comment] 2016-08-08 22:22
I would assume that the attribute would still have to be public for it to work

**Comment by MscrmTools** [comment] 2016-08-09 03:13
Yes, already tried it, does not work

**Comment by shytikov** [comment] 2016-08-09 05:43
Are we on the same page: public attribute, but early bound classes are internal? So assembly is still maked, but classes are (in theory) hidden from other assemblies?

**Comment by shytikov** [comment] 2016-08-09 06:50
I'm convinced, that the only possible solution in this case — enhance our plugin system to use `AppDomains`. 

The situation we're facing is the archetypal case for such approach. The CRM itself uses `AppDomains` for plugins isolation. This won't be easy part of development, but unless we don't want to plugins affect whole application, we need to accomplish that.

**Comment by macacq** [comment] 2016-08-10 19:07
I've implemented workaround on my end: removed early bound attribute from assembly and started casting entities to generated classes manually. Turned to be simpler than I thought: 

https://github.com/macacq/PluginRegistration/blob/master/Xrm.Sdk.PluginRegistration/Entities/Transformation/Magic.cs

Normally it's quite easy to use: retrieve entities, no matter are they late bound or early bound, call `Magic.CastTo<Type>(entity)` as part of `Select` LINQ statement, and here you are! Entities are safely resolved to early bound classes defined in your assembly. Here is an example:

https://github.com/macacq/PluginRegistration/blob/master/Xrm.Sdk.PluginRegistration/Helpers/OrganizationHelper.cs#L745

I believe, approach could be optimized, for example, it should be possible to overload cast operator, so explicit call to `Magic` class won't be needed.

I believe also, that approach could fail in some cases, which I've not tested. For example, complex queries with linked entities. But so far it was working for me...

You could try as well: https://www.nuget.org/packages/Xrm.Sdk.PluginRegistration/3.0.7

**Comment by daryllabar** [comment] 2016-08-11 15:01
I think I have a work around...

The error in the log shows this as the cause

> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
> Method	: HandleReturnMessage
> Date	: 8/11/2016
> Time	: 9:50:42 AM
> Error	: A proxy type with the name pluginassembly has been defined by another assembly. Current type: PluginRegistrationTool.Entities.PluginAssembly, PluginRegistration, Version=3.0.4.0, Culture=neutral, PublicKeyToken=null, Existing type: DLaB.Xrm.Entities.PluginAssembly, DLaB.Xrm.Entities, Version=8.1.0.1, Culture=neutral, PublicKeyToken=null
> Parameter name: pluginassembly
> Stack Trace	: Server stack trace: 
>    at Microsoft.Xrm.Sdk.AppDomainBasedKnownProxyTypesProvider.AddTypeMapping(Assembly assembly, Type type, String proxyName)
>    at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.LoadKnownTypes(Assembly assembly)
>    at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.RegisterAssembly(Assembly assembly)
>    at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.InitializeLoadedAssemblies()
>   at Microsoft.Xrm.Sdk.KnownProxyTypesProvider.GetInstance(Boolean supportIndividualAssemblies)
>   at Microsoft.Xrm.Sdk.ProxySerializationSurrogate.System.Runtime.Serialization.IDataContractSurrogate. GetObjectToSerialize(Object obj, Type targetType)
>  ---- SNIP ----

So what is happening, is prior to serialization, it is attempting to load all Assembly Types.
In the constructor of the `AppDomainBasedKnownProxyTypesProvider`, it adds a event handler for any new assembly types loaded, and calls `KnownProxyTypesProvider.InitializeLoadedAssemblies` which processes all current assemblies.  
```
internal AppDomainBasedKnownProxyTypesProvider()
{
  AppDomainBasedKnownProxyTypesProvider._nameMap = new Dictionary<string, Type>();
  AppDomainBasedKnownProxyTypesProvider._typeMap = new Dictionary<Type, string>();
  AppDomain.CurrentDomain.AssemblyLoad += new AssemblyLoadEventHandler(this.CurrentDomain_AssemblyLoad);
  this.InitializeLoadedAssemblies();
}
```
This then blows chow when the same entity is defined for a class more than once.

The short work around is to initialize the `KnownProxyTypesProvider.GetInstance` first (it's an internal static method, so it can be called via reflection) and pass in false as the parameter, before loading any plugin types.  Then remove the AppDomain.CurrentDomain.AssemblyLoad (using more reflection with something like [this](http://stackoverflow.com/questions/91778/how-to-remove-all-event-handlers-from-a-control)).

This will effectively remove all Default Early Binding, and allow the connection to succeed to the CRM.  We can then call the EnableProxyTypes(Assembly) as desired for each plugin.  So there is no pain to those using late bound, and those that want to use early, must subscribe with their specific dll.  This would also have the added benefit of improving load times since it doesn't have to analyze every assembly added...


Would this be something that we want me to look into?

**Comment by shytikov** [comment] 2016-08-11 15:06
It would be nice!

And I from my side can take a look on AppDomain isolation, I believe one way or another we would have to have it after all.

**Comment by daryllabar** [comment] 2016-08-11 15:12
App Domain would be great, since it would be "supported" ie, not require Reflection.  I'll work on it tonight and see what i come up with...

**Comment by daryllabar** [comment] 2016-08-12 06:20
Partial success.  See  my PR [Hack for Early Bound Assemblies #470](Hack for Early Bound Assemblies #470) for more details.  This allows the XTB to completely support non-OrganizationServiceContext interactions with CRM.  It also (as long as the plugin implements IEarlyBoundProxy) will work for Assembly dll per XTB instance.  So if I only open up one plugin (or 6 plugins that share the same Early Bound Types Assembly), it will work just fine.

**Comment by shytikov** [comment] 2016-08-12 06:58
I will reference here the issue I've created a year ago #158 regarding AppDomains.

**Comment by daryllabar** [comment] 2016-08-12 14:25
@shytikov you mention that there was one issue that you couldn't overcome with async and custom actions when attempting to have isolated App Domains.  Do you remember what that was?

**Comment by shytikov** [comment] 2016-08-12 14:48
Not really, these issues may not even be relevant now, since `XTB`'s skeleton was mostly rewritten...

**Comment by shytikov** [comment] 2016-08-12 15:47
I think we need to sit and design AppDomain change properly. Not to overcomplicate things.

I trying to picture per plugin separation, and for me it looks that we will end up having sever AppDomains with several XTB instances each one runs only one active plugin.

And! Interplugin message bus communication will not be possible (since objects will not be able to cross AppDomain boundaries)

Now I don't like idea hack around WinForms AppDomain issues also. Instead I would create singe huge AppDomain for all the GUI stuff (XTB core and plugins) forbid access to Internet for it — wait for explanation — and would create singe small AppDomain per every plugin connection to CRM.

Results:

* GUI will run as solid object, but sandboxed into separate AppDomain with no network access — customers may be sure, that plugin will not expose any data to outside world.
* All network requests would be done through XTB Connection module. There will be several sandboxed instances of it. Each one will be talking to the respective plugin. So plugin will not be able to read credentials or access to network layer in any other way.

**Comment by daryllabar** [comment] 2016-08-15 16:50
So what's the big thing preventing us from having separate App Domains?

**Comment by shytikov** [comment] 2016-08-15 19:11
It depends how to divide. If put every plugin with GUI in separate AppDomain we won't be able to assemble components into single window application, because WinForms does not support combining content from different AppDomains in one window. Though hacks available (haven't tried yet).

Another approach, what I've mentioned in my comment above. Isolate `OrganizationService` instances for each plugin. But this means heavily rewriting core, to route calls to proper instances of `OrganizationService`. And here we could include your PR of specifying early-bound assembly, which will be valid in this AppDomain only.

But I believe we need some kind of blessing from @MscrmTools to start working on PRs...

**Comment by daryllabar** [comment] 2016-08-15 19:58
Or I get help figuring out why the standard option for loading the AssemblyBasedKnownProxyTypesProvider isn't working...

**Comment by MscrmTools** [comment] 2016-08-15 20:09
I'm totally honest here: I'm not skilled enough in coding to improve XTB to AppDomains as discussed in previous comment.
But you do have my blessing to improve it and implement this in XTB

**Comment by shytikov** [comment] 2016-08-16 08:09
I can try to implement my vision to `AppDomains` and then @daryllabar could enhance this approach with his early-bound resolve hack.

**Comment by MscrmTools** [comment] 2017-04-28 07:15
Closing this issue since it won't be able to implement separate AppDomains

**Closed by MscrmTools** 2017-04-28 07:15 UTC
Labels: enhancement
