### ISSUE TITLE
Easy Translator imports Site Map titles as descriptions

### ISSUE THREAD

**Issue by liorabel** [MscrmTools/XrmToolBox#228] opened 2015-09-02 13:18 UTC
Also overwrites SubArea descriptions with the parent Group's description.

**Comment by rappen** [comment] 2015-09-02 13:22
Are you sure you have the latest version of XTB? I think I have seen this problem, long ago...

**Comment by liorabel** [comment] 2015-09-02 13:36
XTB v1.2015.7.31.
Working against CRM 2013 SP1 UR2 on premise.

It has been doing that to me all day now. When I use SiteMap Editor to fix the titles and descriptions, Easy Translator will break them again the next time...

**Comment by MscrmTools** [comment] 2015-09-02 13:49
I saw something like this lately in a pull request.

I will work on this

**Comment by MscrmTools** [comment] 2015-09-07 12:08
Ok, I do not reproduce with my latest version as per below screenshots

Translation file (I put title and desc in corresponding cells to identify them clearly in CRM)
<img width="197" alt="sitemaptranslationfile" src="https://cloud.githubusercontent.com/assets/10774317/9716391/61250132-5569-11e5-8887-dfe393e88c59.png">

Result
<img width="311" alt="sitemaptranslation" src="https://cloud.githubusercontent.com/assets/10774317/9716430/b781f0bc-5569-11e5-8132-b57e90f4a7df.png">

But I cannot say if this has been fixed in the latest bits or before...

Anyway, it seems to be already fixed

**Closed by MscrmTools** 2015-09-07 12:08 UTC
Labels: bug

**Comment by liorabel** [comment] 2015-09-07 12:12
Did you try this with multiple languages and also switching between them in the UI?
The system this failed on for me has 6+ different languages installed.

In any case, I will test the new version when it is released and reopen the issue if it still exists.

**Comment by MscrmTools** [comment] 2015-09-07 12:53
ok, thank you for the feedback

**Comment by MscrmTools** [comment] 2015-09-07 12:58
I will test it again, I have a two langages enabled organization available

**Comment by MscrmTools** [comment] 2015-09-07 13:35
I confirm with two langages (as per screenshots below)
<img width="215" alt="sitemap1036" src="https://cloud.githubusercontent.com/assets/10774317/9717808/f8934108-5575-11e5-8a1d-9505b571ad22.png">
<img width="309" alt="sitemap1033" src="https://cloud.githubusercontent.com/assets/10774317/9717809/fabdef50-5575-11e5-9525-c7c72d93dcd0.png">
