### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by JadynWong** [MscrmTools/XrmToolBox#861] opened 2019-05-05 08:30 UTC
It is not has any error.But when i open xrmtoolbox, it only show title and blank screen.If I move tab to a window or top or left or right or bottom,it will show content and normal work.

I tried to reset and replace the computer. It didn't change at all.
os:windows10 1809
It bothers me.
![Annotation 2019-05-05 161839](https://user-images.githubusercontent.com/13699353/57190836-91c2af00-6f51-11e9-9728-df07e0691e8f.png)
![Annotation 2019-05-05 161915](https://user-images.githubusercontent.com/13699353/57190837-91c2af00-6f51-11e9-850d-b3160e253dd4.png)
![Annotation 2019-05-05 161925](https://user-images.githubusercontent.com/13699353/57190838-94250900-6f51-11e9-9bf4-c9494175f236.png)

**Comment by MscrmTools** [comment] 2019-05-10 12:34
Never seen it.
It seems you are using black screen mode. Is it the same with white screen mode?

**Comment by JadynWong** [comment] 2019-05-10 15:53
> Never seen it.
> It seems you are using black screen mode. Is it the same with white screen mode?

Yes.It is also same blank in white theme .
This is another pc with new environment
![image](https://user-images.githubusercontent.com/13699353/57540005-49a2f280-737e-11e9-88de-45c52e9c0d4f.png)

**Comment by MscrmTools** [comment] 2019-05-24 11:54
I just reproduced the issue... O_o 

Need to find out what the problem is now...

**Comment by MscrmTools** [comment] 2019-05-24 11:55
Ouch, I just applied some Windows Update yesterday... just hope this is not related

**Comment by JadynWong** [comment] 2019-05-24 13:29
> Ouch, I just applied some Windows Update yesterday... just hope this is not related

Hope so.

**Comment by MscrmTools** [comment] 2019-05-27 13:52
So, it does not seem related to a Windows update, even if I still don't know what the cause is...

Using my current version (the same as yours), I don't have the issue
Using my dev version (on the same computer), I reproduce the issue

**Comment by JadynWong** [comment] 2019-05-31 07:33
Still can't find the reason.It is very strange

**Comment by MscrmTools** [comment] 2019-06-06 05:00
Problem fixed on my side. It was a scaling issue.
If you had the problem, then I imagine you forked this project and applied some changes yourself since the problem was introduced by Visual Studio

**Closed by MscrmTools** 2019-06-06 05:00 UTC

**Comment by JadynWong** [comment] 2019-06-07 08:41
@MscrmTools Thanks.I will try it

**Comment by mekkoo** [comment] 2020-05-27 10:41
I'm facing the same problem with v1.2020.5.39.
Thank you for always developing.

https://monosnap.com/file/OxQypyZ8usaKJiJT4IC98QGtuNN3Ai

**Comment by JadynWong** [comment] 2020-05-27 10:47
@mekkoo 

> I'm facing the same problem with v1.2020.5.39.
> Thank you for always developing.
> 
> https://monosnap.com/file/OxQypyZ8usaKJiJT4IC98QGtuNN3Ai

You can try to run it in Windows 7 compatibility mode, I can't promise, but it works sometimes.

**Comment by mekkoo** [comment] 2020-08-05 04:47
Thank you for advice. Afterwards, I resolved this problem.
I checked "high dpi scale override".

![image](https://user-images.githubusercontent.com/282262/89372728-e7bc6e80-d721-11ea-8598-cd49aa97f556.png)
