### ISSUE TITLE
I am not able to connect to the server  i am getting this( unhanded exception has occured in the application  could not load file or assembly csv helper  version=6.0.0.0.   this popup occurs

### ISSUE THREAD

**Issue by teja25** [MscrmTools/XrmToolBox#737] opened 2018-03-26 20:01 UTC
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by MscrmTools** [comment] 2018-03-26 21:09
What XrmToolBox version?

**Comment by teja25** [comment] 2018-03-27 01:22
v1.2018.1.20

**Comment by teja25** [comment] 2018-03-27 01:24
it is v1.2018.1.20

**Comment by MscrmTools** [comment] 2018-03-27 03:51
Please update to the latest version. You should see a popup that tells you what plugin is responsible for the crash so that you can delete it

**Comment by teja25** [comment] 2018-03-27 13:46
![2018-03-26_14-57-23](https://user-images.githubusercontent.com/4304455/37971321-40c09558-319b-11e8-80db-16c86c2db6f2.png)
This is error i am getting  still.
Thanks.

**Comment by MscrmTools** [comment] 2018-03-27 13:58
And you are still not on the latest version. Please use the latest version, you should have a detailed error with the faulting plugin

**Comment by teja25** [comment] 2018-03-27 14:00
ok thanks

**Comment by MscrmTools** [comment] 2018-03-29 11:28
Duplicate of #725

**Closed by MscrmTools** 2018-03-29 11:28 UTC
