### ISSUE TITLE
How to consistently get the connection timeout to be enfoced?

### ISSUE THREAD

**Issue by stevekmicrosoft** [MscrmTools/XrmToolBox#800] opened 2018-08-21 21:02 UTC
I set the connection timeout to be more than 2:00 minutes in the connection dialogue. The majority of the time it seems that the 2:00 minute timeout continues to be used. On a couple of occasions the plugins seemed to use the modified timeout, but I cannot consistently create the process in which the modified timeout is enforced. I have deleted connections and re-added, edited the connection, and closed/re-opened the app. Any ideas?

**Comment by rappen** [comment] 2018-08-22 06:10
Do you see consistent behavior which tools respect the timeout and which don't?

**Comment by stevekmicrosoft** [comment] 2018-08-22 14:04
The three plugins I am using all behave the same way. I understand there is a difference between "Service Timeout" and "SQL Connection Timeout" so, perhaps this is what is going on. The SQL timeout is not something that can be set in a query (from my understanding).

**Comment by MscrmTools** [comment] 2018-09-11 05:53
If the problem is from SQL timeout, I can't control it indeed. 

Closing the issue for now. Reopen it if needed

**Closed by MscrmTools** 2018-09-11 05:53 UTC
