### ISSUE TITLE
BUG: Chart Manager

### ISSUE THREAD

**Issue by edmarveras** [MscrmTools/XrmToolBox#552] opened 2017-01-19 14:28 UTC
After changing the Data Description of a chart, there is no save button therefore we can not save the changes to the chart.

![chart manager](https://cloud.githubusercontent.com/assets/25225827/22110390/579e9eb0-de3a-11e6-9567-3f471fae088b.png)

**Comment by MscrmTools** [comment] 2017-01-19 14:40
Looks like a display issue!
thanks for reporting it!

**Comment by MscrmTools** [comment] 2017-01-19 14:43
What is your version of XrmToolBox and Chart Manager?
I do not reproduce

**Comment by edmarveras** [comment] 2017-01-19 15:02
XrmToolBox - v1.2016.11.4
Chart Manager - v1.2016.8.23

Just updated both.

**Comment by MscrmTools** [comment] 2017-01-19 15:12
what if you maximize the window?

**Comment by edmarveras** [comment] 2017-01-19 15:33
Same thing, it does not show any button do save.

**Comment by edmarveras** [comment] 2017-01-19 15:34
Full screen print:
![image](https://cloud.githubusercontent.com/assets/25225827/22112992/a4d1796a-de43-11e6-8fcf-715613573bec.png)

**Comment by edmarveras** [comment] 2017-01-19 15:35
I have even hidden the Windows Toolbar and nothing.

**Comment by MscrmTools** [comment] 2017-01-19 15:38
I have the exact same versions than you but everything seems ok

![image](https://cloud.githubusercontent.com/assets/10774317/22113152/a43b34ec-de65-11e6-8dc9-a637713a725d.png)

Do you have a high DPI monitor?

**Comment by edmarveras** [comment] 2017-01-19 16:01
1366x768 14inch Dell notebook screen.
I tryed all resolutions down to 800x600 and still the same thing.

**Comment by edmarveras** [comment] 2017-01-20 13:02
Any News on this issue? Anything else I could try on my environment to test?
Many thanks.

**Comment by rajyraman** [comment] 2017-01-27 00:07
You could probably use some tips from the Plugin Registration tool thread-> https://community.dynamics.com/crm/f/117/t/179132

**Comment by MscrmTools** [comment] 2017-03-21 17:17
I hope this is resolved in the latest release. Please test and open a new issue in the new repository if needed

**Closed by MscrmTools** 2017-03-21 17:17 UTC
Labels: bug
