### ISSUE TITLE
XRMToolbox doesn't open after update

### ISSUE THREAD

**Issue by dirasmitabasu** [MscrmTools/XrmToolBox#844] opened 2019-02-28 22:17 UTC
After an update, XRMToolBox is unable to reopen. Here's the screenshot.
![xrmtoolbox](https://user-images.githubusercontent.com/48103480/53602410-b038b280-3b7c-11e9-8a4e-c69b2cb6336d.PNG)
The path to my XrmToolBox is C:\CRM Tools\XrmToolbox

**Comment by WhiteyC** [comment] 2019-03-01 01:32
Great, just when I have a client development the update crashes the app. Please find a fix ASAP.

**Comment by edipple** [comment] 2019-03-01 03:29
Same issue for me.   Now I have to try and rollback

**Comment by MscrmTools** [comment] 2019-03-01 06:19
Just delete the Plugins.zip file in your XrmToolBox and you are good to go

**Comment by MscrmTools** [comment] 2019-03-01 06:20
As for the original error, the problem is with auto updated and is fixed in this release, just run your XrmToolBox as usual and you will see it has been updated correctly

**Comment by rappen** [comment] 2019-03-01 07:58
@WhiteyC and @edipple I understand your frustration, but still encourage you when providing feedback to remember this tool is provided to you and us all completely for free, the only one paying for us to use it is Tanguy himself, with his time and expertise. Sarcastic tone is hardly encouraging for him to continue to give us all this.
The alternative we have, if we don't appreciate how it is done, is to use what MS provides instead. 

Also from just looking at your error message doesn't seem to be related to the original issue, creating a new issue is then preferred.

**Comment by MscrmTools** [comment] 2019-03-01 08:13
Both issues are now fixed

**Closed by MscrmTools** 2019-03-01 08:13 UTC
